import type {ConcreteTreeNode} from "../../ConcreteTreeNode.ts";
import type {FunctionHeaderSegmentsSeparatedRestSegmentsConcreteTreeNodeChildren} from "./FunctionHeaderSegmentsSeparatedRestSegmentsConcreteTreeNodeChildren.ts";
import type {functionHeaderSegmentsSeparatedRestSegmentsConcreteTreeNodeTypeName} from "./functionHeaderSegmentsSeparatedRestConcreteTreeNodeTypeName.ts";

export type FunctionHeaderSegmentsSeparatedRestSegmentsConcreteTreeNode = ConcreteTreeNode<
	typeof functionHeaderSegmentsSeparatedRestSegmentsConcreteTreeNodeTypeName,
	FunctionHeaderSegmentsSeparatedRestSegmentsConcreteTreeNodeChildren
>;
